### ISSUE TITLE
Pilares - Ilustraciones derecha/izquierda

### ISSUE THREAD

**Issue by RosanaRufer** [lean-mind/leanmindweb#2]
La sección de los pilares tiene dos modos que se cambian de manera aleatoria a)derecha b)izquierda.

Cuando estamos con el texto en la izquierda, la parte de la derecha se queda en blanco

![image](https://user-images.githubusercontent.com/4906291/55862398-498db800-5b70-11e9-9c4d-6fcdb8ee7271.png)

![image](https://user-images.githubusercontent.com/4906291/55862427-5a3e2e00-5b70-11e9-8f8b-ecdae8c9418d.png)

**Comment by mreysei** [comment]
Ya está solucionado y debería funcionar correctamente en la web, si quieres mirar un poco lo que se cambió en ese commit, es este:
https://github.com/lean-mind/leanmindweb/commit/ec41d464f73c2102b628b990620ecbf6140e8e38

Gracias!

**Comment by RosanaRufer** [comment]
@mreysei Asombroso 😮
